# Generated by Django 6.0 on 2026-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_newsletter_portfolio_projectcategory_service_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='module',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='module1',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='module2',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
