# Generated by Django 6.0 on 2026-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_project_module_project_module1_project_module2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('image', models.ImageField(upload_to='team_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('team_module', models.CharField(blank=True, default='General', max_length=100, null=True)),
                ('team_module1', models.CharField(blank=True, default='General', max_length=100, null=True)),
                ('team_module2', models.CharField(blank=True, default='General', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
